package com.csse3200.game.areas.forest;

/**
 * Config class containing all information related to the forest game area.
 */
public class ForestTexturesConfig {
    public static final String[] FOREST_TEXTURES = {
            "images/box_boy_leaf.png",
            "images/tree.png",
            "images/cloud.png",
            "images/seaweed.png",
            "images/starfish.png",
            "images/final_boss_kangaroo.png",
            "images/friendly_npcs/friendly-npcs.png",
            "images/water_boss.png",
            "images/air_boss.png",
            "images/joey.png",
            "images/grass_1.png",
            "images/grass_2.png",
            "images/grass_3.png",
            "images/hex_grass_1.png",
            "images/hex_grass_2.png",
            "images/hex_grass_3.png",
            "images/iso_grass_1.png",
            "images/iso_grass_2.png",
            "images/iso_grass_3.png",
            "images/gt.png",
            "images/dog.png",
            "images/croc.png",
            "images/bird.png",
            "images/Healthpotion.png",
            "images/foodtextures/apple.png",
            "images/foodtextures/oceanfoodtextures/fried-fish.png",
            "images/foodtextures/oceanfoodtextures/shrimp.png",
            "images/foodtextures/airfoodtextures/cloud-cookie.png",
            "images/foodtextures/airfoodtextures/cloudCupcake.png",
            "images/foodtextures/airfoodtextures/cotton-cloud.png",
            "images/hive.png",
            "images/effects.png",
            "images/griffinEffects.png",

            "images/fog-gate.jpg",

            "images/grass_tile_1_around_sand/upper_left_corner_grass_1_around_sand.jpg",
            "images/grass_tile_1_around_sand/upper_middle_grass_1_around_sand.jpg",
            "images/grass_tile_1_around_sand/upper_right_corner_grass_1_around_sand.jpg",
            "images/grass_tile_1_around_sand/left_middle_grass_1_around_sand.jpg",
            "images/grass_tile_1_around_sand/middle_grass_1_around_sand.jpg",
            "images/grass_tile_1_around_sand/right_middle_grass_1_around_sand.jpg",
            "images/grass_tile_1_around_sand/lower_left_corner_grass_1_around_sand.jpg",
            "images/grass_tile_1_around_sand/lower_middle_grass_1_around_sand.jpg",
            "images/grass_tile_1_around_sand/lower_right_corner_grass_1_around_sand.jpg",

            "images/grass_tile_1_around_water/upper_left_corner_grass_1_around_water.jpg",
            "images/grass_tile_1_around_water/upper_middle_grass_1_around_water.jpg",
            "images/grass_tile_1_around_water/upper_right_corner_grass_1_around_water.jpg",
            "images/grass_tile_1_around_water/left_middle_grass_1_around_water.jpg",
            "images/grass_tile_1_around_water/middle_grass_1_around_water.jpg",
            "images/grass_tile_1_around_water/right_middle_grass_1_around_water.jpg",
            "images/grass_tile_1_around_water/lower_left_corner_grass_1_around_water.jpg",
            "images/grass_tile_1_around_water/lower_middle_grass_1_around_water.jpg",
            "images/grass_tile_1_around_water/lower_right_corner_grass_1_around_water.jpg",

            "images/grass_tile_2_around_sand/upper_left_corner_grass_2_around_sand.jpg",
            "images/grass_tile_2_around_sand/upper_middle_grass_2_around_sand.jpg",
            "images/grass_tile_2_around_sand/upper_right_corner_grass_2_around_sand.jpg",
            "images/grass_tile_2_around_sand/left_middle_grass_2_around_sand.jpg",
            "images/grass_tile_2_around_sand/middle_grass_2_around_sand.jpg",
            "images/grass_tile_2_around_sand/right_middle_grass_2_around_sand.jpg",
            "images/grass_tile_2_around_sand/lower_left_corner_grass_2_around_sand.jpg",
            "images/grass_tile_2_around_sand/lower_middle_grass_2_around_sand.jpg",
            "images/grass_tile_2_around_sand/lower_right_corner_grass_2_around_sand.jpg",

            "images/grass_tile_2_around_water/upper_left_corner_grass_2_around_water.jpg",
            "images/grass_tile_2_around_water/upper_middle_grass_2_around_water.jpg",
            "images/grass_tile_2_around_water/upper_right_corner_grass_2_around_water.jpg",
            "images/grass_tile_2_around_water/left_middle_grass_2_around_water.jpg",
            "images/grass_tile_2_around_water/middle_grass_2_around_water.jpg",
            "images/grass_tile_2_around_water/right_middle_grass_2_around_water.jpg",
            "images/grass_tile_2_around_water/lower_left_corner_grass_2_around_water.jpg",
            "images/grass_tile_2_around_water/lower_middle_grass_2_around_water.jpg",
            "images/grass_tile_2_around_water/lower_right_corner_grass_2_around_water.jpg",

            "images/sand_tile_1_around_grass/upper_left_corner_sand_1_around_grass.jpg",
            "images/sand_tile_1_around_grass/upper_middle_sand_1_around_grass.jpg",
            "images/sand_tile_1_around_grass/upper_right_corner_sand_1_around_grass.jpg",
            "images/sand_tile_1_around_grass/left_middle_sand_1_around_grass.jpg",
            "images/sand_tile_1_around_grass/middle_sand_1_around_grass.jpg",
            "images/sand_tile_1_around_grass/right_middle_sand_1_around_grass.jpg",
            "images/sand_tile_1_around_grass/lower_left_corner_sand_1_around_grass.jpg",
            "images/sand_tile_1_around_grass/lower_middle_sand_1_around_grass.jpg",
            "images/sand_tile_1_around_grass/lower_right_corner_sand_1_around_grass.jpg",

            "images/sand_tile_1_around_water/upper_left_corner_sand_1_around_water.jpg",
            "images/sand_tile_1_around_water/upper_middle_sand_1_around_water.jpg",
            "images/sand_tile_1_around_water/upper_right_corner_sand_1_around_water.jpg",
            "images/sand_tile_1_around_water/left_middle_sand_1_around_water.jpg",
            "images/sand_tile_1_around_water/middle_sand_1_around_water.jpg",
            "images/sand_tile_1_around_water/right_middle_sand_1_around_water.jpg",
            "images/sand_tile_1_around_water/lower_left_corner_sand_1_around_water.jpg",
            "images/sand_tile_1_around_water/lower_middle_sand_1_around_water.jpg",
            "images/sand_tile_1_around_water/lower_right_corner_sand_1_around_water.jpg",

            "images/sand_tile_2_around_grass/upper_left_corner_sand_2_around_grass.jpg",
            "images/sand_tile_2_around_grass/upper_middle_sand_2_around_grass.jpg",
            "images/sand_tile_2_around_grass/upper_right_corner_sand_2_around_grass.jpg",
            "images/sand_tile_2_around_grass/left_middle_sand_2_around_grass.jpg",
            "images/sand_tile_2_around_grass/middle_sand_2_around_grass.jpg",
            "images/sand_tile_2_around_grass/right_middle_sand_2_around_grass.jpg",
            "images/sand_tile_2_around_grass/lower_left_corner_sand_2_around_grass.jpg",
            "images/sand_tile_2_around_grass/lower_middle_sand_2_around_grass.jpg",
            "images/sand_tile_2_around_grass/lower_right_corner_sand_2_around_grass.jpg",

            "images/sand_tile_2_around_water/upper_left_corner_sand_2_around_water.jpg",
            "images/sand_tile_2_around_water/upper_middle_sand_2_around_water.jpg",
            "images/sand_tile_2_around_water/upper_right_corner_sand_2_around_water.jpg",
            "images/sand_tile_2_around_water/left_middle_sand_2_around_water.jpg",
            "images/sand_tile_2_around_water/middle_sand_2_around_water.jpg",
            "images/sand_tile_2_around_water/right_middle_sand_2_around_water.jpg",
            "images/sand_tile_2_around_water/lower_left_corner_sand_2_around_water.jpg",
            "images/sand_tile_2_around_water/lower_middle_sand_2_around_water.jpg",
            "images/sand_tile_2_around_water/lower_right_corner_sand_2_around_water.jpg",

            "images/water_tile_1_around_grass/upper_left_corner_water_1_around_grass.jpg",
            "images/water_tile_1_around_grass/upper_middle_water_1_around_grass.jpg",
            "images/water_tile_1_around_grass/upper_right_corner_water_1_around_grass.jpg",
            "images/water_tile_1_around_grass/left_middle_water_1_around_grass.jpg",
            "images/water_tile_1_around_grass/middle_water_1_around_grass.jpg",
            "images/water_tile_1_around_grass/right_middle_water_1_around_grass.jpg",
            "images/water_tile_1_around_grass/lower_left_corner_water_1_around_grass.jpg",
            "images/water_tile_1_around_grass/lower_middle_water_1_around_grass.jpg",
            "images/water_tile_1_around_grass/lower_right_corner_water_1_around_grass.jpg",

            "images/water_tile_1_around_sand/upper_left_corner_water_1_around_sand.jpg",
            "images/water_tile_1_around_sand/upper_middle_water_1_around_sand.jpg",
            "images/water_tile_1_around_sand/upper_right_corner_water_1_around_sand.jpg",
            "images/water_tile_1_around_sand/left_middle_water_1_around_sand.jpg",
            "images/water_tile_1_around_sand/middle_water_1_around_sand.jpg",
            "images/water_tile_1_around_sand/right_middle_water_1_around_sand.jpg",
            "images/water_tile_1_around_sand/lower_left_corner_water_1_around_sand.jpg",
            "images/water_tile_1_around_sand/lower_middle_water_1_around_sand.jpg",
            "images/water_tile_1_around_sand/lower_right_corner_water_1_around_sand.jpg",

            "images/water_tile_2_around_grass/upper_left_corner_water_2_around_grass.jpg",
            "images/water_tile_2_around_grass/upper_middle_water_2_around_grass.jpg",
            "images/water_tile_2_around_grass/upper_right_corner_water_2_around_grass.jpg",
            "images/water_tile_2_around_grass/left_middle_water_2_around_grass.jpg",
            "images/water_tile_2_around_grass/middle_water_2_around_grass.jpg",
            "images/water_tile_2_around_grass/right_middle_water_2_around_grass.jpg",
            "images/water_tile_2_around_grass/lower_left_corner_water_2_around_grass.jpg",
            "images/water_tile_2_around_grass/lower_middle_water_2_around_grass.jpg",
            "images/water_tile_2_around_grass/lower_right_corner_water_2_around_grass.jpg",

            "images/water_tile_2_around_sand/upper_left_corner_water_2_around_sand.jpg",
            "images/water_tile_2_around_sand/upper_middle_water_2_around_sand.jpg",
            "images/water_tile_2_around_sand/upper_right_corner_water_2_around_sand.jpg",
            "images/water_tile_2_around_sand/left_middle_water_2_around_sand.jpg",
            "images/water_tile_2_around_sand/middle_water_2_around_sand.jpg",
            "images/water_tile_2_around_sand/right_middle_water_2_around_sand.jpg",
            "images/water_tile_2_around_sand/lower_left_corner_water_2_around_sand.jpg",
            "images/water_tile_2_around_sand/lower_middle_water_2_around_sand.jpg",
            "images/water_tile_2_around_sand/lower_right_corner_water_2_around_sand.jpg",

            "images/tiles_with_corners/Grass_tile_with_sand_corner.png",
            "images/tiles_with_corners/Grass_tile_with_water_corner.png",
            "images/tiles_with_corners/Sand_tile_with_grass_corner.png",

            "images/top_left_grass.png",
            "images/top_middle_grass.png",
            "images/top_right_grass.png",
            "images/middle_left_grass.png",
            "images/middle_grass.png",
            "images/middle_right_grass.png",
            "images/lower_left_grass.png",
            "images/lower_middle_grass.png",
            "images/lower_right_grass.png",
            "images/full_sand_tile.png",
            "images/dog.png",
            "images/croc.png",
            "images/bird.png",
            "images/Healthpotion.png",
            "images/foodtextures/apple.png",
            "images/foodtextures/carrot.png",
            "images/foodtextures/Milk.png",
            "images/foodtextures/Sushi.png",
            "images/foodtextures/chicken_leg.png",
            "images/foodtextures/meat.png",
            "images/foodtextures/candy.png",
            "images/potiontexture/speed.png",
            "images/potiontexture/defense.png",
            "images/potiontexture/attack.png",
            "images/wolf.png",
    };

    public static final String[] FOREST_TEXTURE_ATLASES = {
            "images/terrain_iso_grass.atlas",
            "images/chicken.atlas",
            "images/frog.atlas",
            "images/monkey.atlas",
            "images/banana.atlas",
            "images/effects.atlas",
            "images/griffinEffects.atlas",
            "images/bear.atlas",
            "images/eel.atlas",
            "images/friendly-eel.atlas",
            "images/octopus.atlas",
            "images/pigeon.atlas",
            "images/friendly-pigeon.atlas",
            "images/bee.atlas",
            "images/friendly-bee.atlas",
            "images/bigsawfish.atlas",
            "images/macaw.atlas",
            "images/banana.atlas",
            "images/orb.atlas",
            "images/worm.atlas",
            "images/friendly_npcs/Cow.atlas",
            "images/friendly_npcs/Fish.atlas",
            "images/friendly_npcs/snake.atlas",
            "images/friendly_npcs/lion.atlas",
            "images/friendly_npcs/eagle.atlas",
            "images/friendly_npcs/turtle.atlas",
            "images/friendly_npcs/magpie.atlas",
            "images/final_boss_kangaroo.atlas",
            "images/water_boss.atlas",
            "images/air_boss.atlas",
            "images/joey.atlas",
            "images/enemy-frog.atlas",
            "images/enemy-monkey.atlas",
            "images/enemy-chicken.atlas",
            "images/enemy-bear.atlas",
            "images/enemy-chicken.atlas",
            "images/wolf.atlas",
            "images/hive.atlas",
            "images/friendly-octopus.atlas",
            "images/friendly-macaw.atlas"
    };

    private ForestTexturesConfig() {
        throw new IllegalArgumentException("Do not instantiate static util class!");
    }
}
