@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.csse3200.game.components.quests.QuestBasic",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1184530847 { 
   	label=csse3200
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_144169823 { 
   	label=game
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   AITaskComponent570749180[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AITaskComponent</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   currentTask: PriorityTask [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   priorityTasks: List&lt;PriorityTask&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addTask(task: PriorityTask): AITaskComponent</TD></TR>
<TR><TD ALIGN="LEFT" >- changeTask(desiredTask: PriorityTask)</TD></TR>
<TR><TD ALIGN="LEFT" >+ dispose()</TD></TR>
<TR><TD ALIGN="LEFT" >+ update()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AbstractQuest257252461[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AbstractQuest</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   currentTaskIndex: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   isAchievement: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   isActive: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   isFailed: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   isSecretQuest: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   questDescription: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   questDialogue: Map&lt;DialogueKey, String[]&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >#   questName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   tasks: List&lt;Task&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ failQuest()</TD></TR>
<TR><TD ALIGN="LEFT" >+ getDialogue(npcName: String): String[]</TD></TR>
<TR><TD ALIGN="LEFT" >+ progressQuest()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

DialogueKey257252461[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DialogueKey</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   npcName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   progressionLevel: Integer [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

QuestBasic257252461[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)QuestBasic</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

QuestDisplay1650851073[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)QuestDisplay</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   background: Table [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   eventService: EventService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   questComparator: Comparator&lt;AbstractQuest&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   rootTable: Table [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- addActors()</TD></TR>
<TR><TD ALIGN="LEFT" >- addQuestComponents(table: Table, quest: AbstractQuest)</TD></TR>
<TR><TD ALIGN="LEFT" >- addQuestsCompletedLabel(table: Table)</TD></TR>
<TR><TD ALIGN="LEFT" >- addTaskHints(table: Table, quest: AbstractQuest)</TD></TR>
<TR><TD ALIGN="LEFT" >+ create()</TD></TR>
<TR><TD ALIGN="LEFT" >- determineQuestColor(quest: AbstractQuest): Color</TD></TR>
<TR><TD ALIGN="LEFT" >+ dispose()</TD></TR>
<TR><TD ALIGN="LEFT" ># draw(batch: SpriteBatch)</TD></TR>
<TR><TD ALIGN="LEFT" >- exitMenu()</TD></TR>
<TR><TD ALIGN="LEFT" >- makeMenuBtns(): Table</TD></TR>
<TR><TD ALIGN="LEFT" >- makeSliders(): Table</TD></TR>
<TR><TD ALIGN="LEFT" >+ update()</TD></TR>
<TR><TD ALIGN="LEFT" >- updateQuestsCompletedLabel(table: Table, questList: List&lt;QuestBasic&gt;)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

QuestManager257252461[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)QuestManager</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   eventService: EventService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   questComplete: Sound [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   quests: HashMap&lt;String, QuestBasic&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   relevantQuests: Map&lt;String, String[]&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addQuest(quest: QuestBasic)</TD></TR>
<TR><TD ALIGN="LEFT" >- canProgressQuest(quest: QuestBasic, taskName: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- completeTask(quest: QuestBasic)</TD></TR>
<TR><TD ALIGN="LEFT" >+ failQuest(questName: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getDialogue(npcName: String): String[]</TD></TR>
<TR><TD ALIGN="LEFT" >+ getQuest(questName: String): QuestBasic</TD></TR>
<TR><TD ALIGN="LEFT" >- handleQuestCompletion(quest: QuestBasic)</TD></TR>
<TR><TD ALIGN="LEFT" >+ progressQuest(questName: String, taskName: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- subscribeToQuestEvents(quest: QuestBasic)</TD></TR>
<TR><TD ALIGN="LEFT" >- testQuests()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

RenderComponent954639696[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)RenderComponent</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ compareTo(o: Renderable): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ create()</TD></TR>
<TR><TD ALIGN="LEFT" >+ dispose()</TD></TR>
<TR><TD ALIGN="LEFT" ># draw(batch: SpriteBatch)</TD></TR>
<TR><TD ALIGN="LEFT" >+ render(batch: SpriteBatch)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

RenderService954639696[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)RenderService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   debugRenderer: DebugRenderer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   renderables: SortedIntMap&lt;Array&lt;Renderable&gt;&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   stage: Stage [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ dispose()</TD></TR>
<TR><TD ALIGN="LEFT" >+ register(renderable: Renderable)</TD></TR>
<TR><TD ALIGN="LEFT" >+ render(batch: SpriteBatch)</TD></TR>
<TR><TD ALIGN="LEFT" >+ unregister(renderable: Renderable)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Renderer954639696[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Renderer</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   batch: SpriteBatch [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   camera: CameraComponent [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   debugRenderer: DebugRenderer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   gameWidth: float [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   renderService: RenderService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   stage: Stage [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ dispose()</TD></TR>
<TR><TD ALIGN="LEFT" >- init(camera: CameraComponent, gameWidth: float, batch: SpriteBatch, stage: Stage, renderService: RenderService, debugRenderer: DebugRenderer)</TD></TR>
<TR><TD ALIGN="LEFT" >+ render()</TD></TR>
<TR><TD ALIGN="LEFT" >+ resize(width: int, height: int)</TD></TR>
<TR><TD ALIGN="LEFT" >- resizeCamera(screenWidth: int, screenHeight: int)</TD></TR>
<TR><TD ALIGN="LEFT" >- resizeStage(screenWidth: int, screenHeight: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Task257252461[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Task</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   completed: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   description: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   failed: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   hint: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   requiredTriggers: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   taskName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   triggerCount: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ failTask()</TD></TR>
<TR><TD ALIGN="LEFT" >+ handleEvent()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Terminal1764509094[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Terminal</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   commands: Map&lt;String, Command&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   enteredMessage: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   isOpen: boolean [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addCommand(name: String, command: Command)</TD></TR>
<TR><TD ALIGN="LEFT" >+ appendToMessage(character: char)</TD></TR>
<TR><TD ALIGN="LEFT" >+ handleBackspace()</TD></TR>
<TR><TD ALIGN="LEFT" >+ processMessage(): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ toggleIsOpen()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TerminalDisplay1764509094[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TerminalDisplay</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   label: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   terminal: Terminal [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- addActors()</TD></TR>
<TR><TD ALIGN="LEFT" >+ create()</TD></TR>
<TR><TD ALIGN="LEFT" >+ dispose()</TD></TR>
<TR><TD ALIGN="LEFT" >+ draw(batch: SpriteBatch)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TerrainComponent1624884335[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TerrainComponent</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   camera: OrthographicCamera [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   orientation: TerrainOrientation [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tileSize: float [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tiledMap: TiledMap [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tiledMapRenderer: TiledMapRenderer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ dispose()</TD></TR>
<TR><TD ALIGN="LEFT" >+ draw(batch: SpriteBatch)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getMapBounds(layer: int): GridPoint2</TD></TR>
<TR><TD ALIGN="LEFT" >+ tileToWorldPosition(tilePos: GridPoint2): Vector2</TD></TR>
<TR><TD ALIGN="LEFT" >+ tileToWorldPosition(x: int, y: int): Vector2</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TextureRenderComponent954639696[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TextureRenderComponent</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   texture: Texture [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># draw(batch: SpriteBatch)</TD></TR>
<TR><TD ALIGN="LEFT" >+ scaleEntity()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TouchAttackComponent2113102638[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TouchAttackComponent</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   combatStats: CombatStatsComponent [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   hitboxComponent: HitboxComponent [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   knockbackForce: float [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   targetLayer: short [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ create()</TD></TR>
<TR><TD ALIGN="LEFT" >- onCollisionStart(me: Fixture, other: Fixture)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TouchPlayerInputComponent220197757[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TouchPlayerInputComponent</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   walkDirection: Vector2 [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ keyDown(keycode: int): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ keyUp(keycode: int): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ touchDown(screenX: int, screenY: int, pointer: int, button: int): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- triggerWalkEvent()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TouchTerminalInputComponent1764509094[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TouchTerminalInputComponent</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   terminal: Terminal [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ create()</TD></TR>
<TR><TD ALIGN="LEFT" >+ keyDown(keycode: int): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ keyTyped(character: char): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ keyUp(keycode: int): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ scrolled(amountX: float, amountY: float): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UIComponent254041008[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UIComponent</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   stage: Stage [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ create()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
AbstractQuest257252461 -> DialogueKey257252461[label="questDialogue
[0..*]"];
AbstractQuest257252461 -> QuestBasic257252461[arrowhead=none, arrowtail=empty, dir=both];
AbstractQuest257252461 -> Task257252461[label="tasks
[0..*]"];
BodyUserData1074166261 -> Entity52453251[label="entity
[0..1]"];
ChaseTask820797582 -> Entity52453251[label="target
[0..1]"];
ColliderComponent1308264743 -> HitboxComponent1308264743[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> AITaskComponent570749180[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> CameraComponent2113102638[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> ColliderComponent1308264743[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> CombatStatsComponent2113102638[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> Entity52453251[label="entity
[0..1]"];
Component2113102638 -> GhostAnimationController1040480197[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> InputComponent414115698[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> InventoryComponent220197757[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> MainGameActions730501433[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> MainMenuActions730318796[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> PhysicsComponent1308264743[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> PhysicsMovementComponent1308264743[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> PlayerActions220197757[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> QuestManager257252461[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> RenderComponent954639696[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> Terminal1764509094[arrowhead=none, arrowtail=empty, dir=both];
Component2113102638 -> TouchAttackComponent2113102638[arrowhead=none, arrowtail=empty, dir=both];
DefaultTask570749180 -> AITaskComponent570749180[label="owner
[0..1]", arrowhead=none];
Entity52453251 -> Component2113102638[label="components
[0..1]"];
Entity52453251 -> Component2113102638[label="createdComponents
[0..1]"];
EntityService52453251 -> Entity52453251[label="entities
[0..1]"];
ForestGameArea421395894 -> Entity52453251[label="player
[0..1]"];
GameArea421395894 -> Entity52453251[label="areaEntities
[0..*]"];
InputComponent414115698 -> InputDecorator414115698[arrowhead=none, arrowtail=empty, dir=both];
InputComponent414115698 -> KeyboardPlayerInputComponent220197757[arrowhead=none, arrowtail=empty, dir=both];
InputComponent414115698 -> KeyboardTerminalInputComponent1764509094[arrowhead=none, arrowtail=empty, dir=both];
InputComponent414115698 -> TouchPlayerInputComponent220197757[arrowhead=none, arrowtail=empty, dir=both];
InputComponent414115698 -> TouchTerminalInputComponent1764509094[arrowhead=none, arrowtail=empty, dir=both];
InputService414115698 -> InputComponent414115698[label="inputHandlers
[0..*]"];
KeyboardTerminalInputComponent1764509094 -> Terminal1764509094[label="terminal
[0..1]"];
MovementTask820797582 -> PhysicsMovementComponent1308264743[label="movementComponent
[0..1]"];
Overlay1650851073 -> Entity52453251[label="entities
[0..*]"];
PhysicsMovementComponent1308264743 -> PhysicsComponent1308264743[label="physicsComponent
[0..1]"];
PlayerActions220197757 -> PhysicsComponent1308264743[label="physicsComponent
[0..1]"];
QuestDisplay1650851073 -> AbstractQuest257252461[label="questComparator
[0..1]"];
QuestManager257252461 -> QuestBasic257252461[label="quests
[0..*]"];
RenderComponent954639696 -> AnimationRenderComponent954639696[arrowhead=none, arrowtail=empty, dir=both];
RenderComponent954639696 -> TerrainComponent1624884335[arrowhead=none, arrowtail=empty, dir=both];
RenderComponent954639696 -> TextureRenderComponent954639696[arrowhead=none, arrowtail=empty, dir=both];
RenderComponent954639696 -> UIComponent254041008[arrowhead=none, arrowtail=empty, dir=both];
RenderService954639696 -> RenderComponent954639696[label="renderables
[0..1]", arrowhead=none];
Renderer954639696 -> CameraComponent2113102638[label="camera
[0..1]"];
TerminalDisplay1764509094 -> Terminal1764509094[label="terminal
[0..1]"];
TouchAttackComponent2113102638 -> CombatStatsComponent2113102638[label="combatStats
[0..1]"];
TouchTerminalInputComponent1764509094 -> Terminal1764509094[label="terminal
[0..1]"];
UIComponent254041008 -> QuestDisplay1650851073[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml