package com.csse3200.game.areas.terrain.tiles;

import java.util.ArrayList;
import java.util.Arrays;

public class ForestTileConfig {
  private static final String GRASS = "grass";
  private static final String SAND = "sand";
  private static final String WATER = "water";

  private static final TileConfig[] forestMapTiles = {
      new TileConfig(
          "grass2TL",
          "images/grass_tile_2_around_sand/upper_left_corner_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("AAA", "ABB", "ABB", "AAA")),
              GRASS),
      new TileConfig("grass2TM",
          "images/grass_tile_2_around_sand/upper_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("AAA", "ABB", "BBB", "ABB")),
              GRASS),
      new TileConfig("grass2TM",
          "images/grass_tile_2_around_sand/upper_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("AAA", "ABB", "BBB", "ABB")),
              GRASS),
      new TileConfig("grass2TM",
          "images/grass_tile_2_around_sand/upper_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("AAA", "ABB", "BBB", "ABB")),
              GRASS),
      new TileConfig("grass2MM",
          "images/grass_tile_2_around_sand/middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBB", "BBB", "BBB")),
              GRASS),
      new TileConfig("grass2TM",
          "images/grass_tile_2_around_sand/upper_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("AAA", "ABB", "BBB", "ABB")),
              GRASS),
      new TileConfig("grass2TM",
          "images/grass_tile_2_around_sand/upper_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("AAA", "ABB", "BBB", "ABB")),
              GRASS),
      new TileConfig("grass2TM",
          "images/grass_tile_2_around_sand/upper_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("AAA", "ABB", "BBB", "ABB")),
              GRASS),
      new TileConfig("grass2TM",
          "images/grass_tile_2_around_sand/upper_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("AAA", "ABB", "BBB", "ABB")),
              GRASS),
      new TileConfig("grass2TM",
          "images/grass_tile_2_around_sand/upper_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("AAA", "ABB", "BBB", "ABB")),
              GRASS),
      new TileConfig("grass2TM",
          "images/grass_tile_2_around_sand/upper_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("AAA", "ABB", "BBB", "ABB")),
              GRASS),
      new TileConfig("grass2TM",
          "images/grass_tile_2_around_sand/upper_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("AAA", "ABB", "BBB", "ABB")),
              GRASS),
      new TileConfig("grass2TM",
          "images/grass_tile_2_around_sand/upper_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("AAA", "ABB", "BBB", "ABB")),
              GRASS),
      new TileConfig("grass2TM",
          "images/grass_tile_2_around_sand/upper_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("AAA", "ABB", "BBB", "ABB")),
              GRASS),
      new TileConfig("grass2TM",
          "images/grass_tile_2_around_sand/upper_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("AAA", "ABB", "BBB", "ABB")),
              GRASS),
      new TileConfig("grass2TR", 
          "images/grass_tile_2_around_sand/upper_right_corner_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("AAA", "AAA", "BBA", "ABB")),
              GRASS),
      new TileConfig("grass2ML",
          "images/grass_tile_2_around_sand/left_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("ABB", "BBB", "ABB", "AAA")),
              GRASS),
      new TileConfig("grass2ML",
          "images/grass_tile_2_around_sand/left_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("ABB", "BBB", "ABB", "AAA")),
              GRASS),
      new TileConfig("grass2ML",
          "images/grass_tile_2_around_sand/left_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("ABB", "BBB", "ABB", "AAA")),
              GRASS),
      new TileConfig("grass2ML",
          "images/grass_tile_2_around_sand/left_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("ABB", "BBB", "ABB", "AAA")),
              GRASS),
      new TileConfig("grass2ML",
          "images/grass_tile_2_around_sand/left_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("ABB", "BBB", "ABB", "AAA")),
              GRASS),
      new TileConfig("grass2ML",
          "images/grass_tile_2_around_sand/left_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("ABB", "BBB", "ABB", "AAA")),
              GRASS),

      new TileConfig("grass2MM",
          "images/grass_tile_2_around_sand/middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBB", "BBB", "BBB")),
              GRASS),
      new TileConfig("grass2MM1",
          "images/grass_tile_2_around_sand/middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBB", "BBB", "BBB")),
              GRASS),
      new TileConfig("grass2MM2",
          "images/grass_tile_2_around_sand/middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBB", "BBB", "BBB")),
              GRASS),
      new TileConfig("grass2MM3",
          "images/grass_tile_2_around_sand/middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBB", "BBB", "BBB")),
              GRASS),
      new TileConfig("grass2MM4",
          "images/grass_tile_2_around_sand/middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBB", "BBB", "BBB")),
              GRASS),
      new TileConfig("grass2MM5",
          "images/grass_tile_2_around_sand/middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBB", "BBB", "BBB")),
              GRASS),
      new TileConfig("grass2MM6",
          "images/grass_tile_2_around_sand/middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBB", "BBB", "BBB")),
              GRASS),
      new TileConfig("grass2MM7",
          "images/grass_tile_2_around_sand/middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBB", "BBB", "BBB")),
              GRASS),
      new TileConfig("grass2MM8",
          "images/grass_tile_2_around_sand/middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBB", "BBB", "BBB")),
              GRASS),


      new TileConfig("grass2MR",
          "images/grass_tile_2_around_sand/right_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBA", "AAA", "BBA", "BBB")),
              GRASS),
      new TileConfig("grass2MR",
          "images/grass_tile_2_around_sand/right_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBA", "AAA", "BBA", "BBB")),
              GRASS),
      new TileConfig("grass2MR",
          "images/grass_tile_2_around_sand/right_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBA", "AAA", "BBA", "BBB")),
              GRASS),
      new TileConfig("grass2BL",
          "images/grass_tile_2_around_sand/lower_left_corner_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("ABB", "BBA", "AAA", "AAA")),
              GRASS),
      new TileConfig("grass2BM",
          "images/grass_tile_2_around_sand/lower_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBA", "AAA", "BBA")),
              GRASS),
      new TileConfig("grass2BM",
          "images/grass_tile_2_around_sand/lower_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBA", "AAA", "BBA")),
              GRASS),
      new TileConfig("grass2BM",
          "images/grass_tile_2_around_sand/lower_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBA", "AAA", "BBA")),
              GRASS),
      new TileConfig("grass2BM",
          "images/grass_tile_2_around_sand/lower_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBA", "AAA", "BBA")),
              GRASS),
      new TileConfig("grass2BM",
          "images/grass_tile_2_around_sand/lower_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBA", "AAA", "BBA")),
              GRASS),
      new TileConfig("grass2BM",
          "images/grass_tile_2_around_sand/lower_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBA", "AAA", "BBA")),
              GRASS),
      new TileConfig("grass2BM",
          "images/grass_tile_2_around_sand/lower_middle_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBB", "BBA", "AAA", "BBA")),
              GRASS),
      new TileConfig("grass2BR",
          "images/grass_tile_2_around_sand/lower_right_corner_grass_2_around_sand.jpg",
          new ArrayList<>(Arrays.asList("BBA", "AAA", "AAA", "BBA")),
              GRASS),

      new TileConfig("gwsc",
          "images/tiles_with_corners/Grass_tile_with_sand_corner.png",
          new ArrayList<>(Arrays.asList("BBA", "ABB", "ABB", "BBA")),
            GRASS),
      new TileConfig("swgc",
          "images/tiles_with_corners/Sand_tile_with_grass_corner.png",
          new ArrayList<>(Arrays.asList("AAB", "BAA", "BAA", "AAB")),
              SAND),

      new TileConfig("grassslopple2lw",
          "images/sloping_grass_edge_in_sand_tile_2/sloping_grass_edge_in_sand_tile_2_lower_left.jpg",
          new ArrayList<>(Arrays.asList("AAA", "AAA", "BBA", "ABB")),
              GRASS),
      new TileConfig("grassslopple2lr",
          "images/sloping_grass_edge_in_sand_tile_2/sloping_grass_edge_in_sand_tile_2_lower_right.jpg",
          new ArrayList<>(Arrays.asList("AAA", "ABB", "ABB", "AAA")),
              GRASS),
      new TileConfig("grassslopple2ul",
          "images/sloping_grass_edge_in_sand_tile_2/sloping_grass_edge_in_sand_tile_2_upper_left.jpg",
          new ArrayList<>(Arrays.asList("AAB", "AAA", "AAA", "BBA")),
              GRASS),
      new TileConfig("grassslopple2ur",
          "images/sloping_grass_edge_in_sand_tile_2/sloping_grass_edge_in_sand_tile_2_upper_right.jpg",
          new ArrayList<>(Arrays.asList("ABB", "BBA", "AAA", "AAA")),
              GRASS),
  };

  public static TileConfig[] getForestMapTiles() {return forestMapTiles;}

  private ForestTileConfig() {
    throw new IllegalArgumentException("Do not instantiate static util class");
  }
}

